# Build the client
ARG VITE_API_URL

FROM node:20-alpine AS build

WORKDIR /app

RUN corepack enable pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

ENV VITE_API_URL=$VITE_API_URL

RUN pnpm build

# Serve the static files
FROM nginx:alpine

COPY --from=0 /app/dist /usr/share/nginx/html

EXPOSE 80